#! /bin/bash

#$ -cwd
#$ -V
#$ -S /bin/bash


set -e -o pipefail

delineate-estimate-species-partition.py -c run1_spr0.010_.0001.json -t run1_spr0.010_.0001.nex

#python3 /home/jeet/Content/primary/research/delineate/delineate-performance/bin/evaluate-species-partition-estimation.py run1_spr0.010_.0001.json run1_spr0.010_.0001.partition-probs.json > run1_spr0.010_.0001.joint-partition-est-perf.tsv


echo "Job $JOBID completed on $(date --rfc-3339='seconds')"
