#! /bin/bash

#$ -cwd
#$ -V
#$ -S /bin/bash


set -e -o pipefail

delineate-estimate-speciation-completion-rate.py  -c spccomplrate_spr0.050_.0001.json -t spccomplrate_spr0.050_.0001.nex -i -I -l num_lineages:80 -l num_species:29 -l src_filepath:spccomplrate_spr0.050_.0001.nex -l true_speciation_completion_rate:0.05 -l batch_id:megaptera::20181218141844::4231 > spccomplrate_spr0.050_.0001.speciation-rate.tsv


echo "Job $JOBID completed on $(date --rfc-3339='seconds')"
