#! /bin/bash
#PBS -l nodes=ram512

# stop execution of script immediately on any errors
set -e -o pipefail

# if running on an HPC using a job scheduler, change to job directory
cd ${PBS_O_WORKDIR:-$PWD}

# if you have installed delineate in an Anaconda environment, activate it here
# conda activate dev0

# execute the analysis
delineate-estimate partitions \
    -P 0.99 \
    -t lionepha-p095-hkyg.mcct-mean-age.tree.nex \
    -c lionepha.run1.tsv

